### ISSUE TITLE
Logo image file - invalid URL

### ISSUE THREAD

**Issue by joey102030** [ryancramerdesign/AdminThemeUikit#16]
When the url is invalid a broken image is shown in place of the logo, would be good to have a simple check and fallback to the default logo file.

Would be even better to have an image upload field here (and file upload for the 'Primary CSS file') but that would be classed as a feature or improvement.

**Comment by ryancramerdesign** [comment]
I don't think we can do this because the logo needs to be something specified with a URL, and that URL could very well be at a different hostname. It's not practical for us to check for a logo 404 on every request. But since a bad logo URL would appear as a broken image immediately, I think this is probably enough to indicate that there's a problem with it.
