### ISSUE TITLE
Drop down menus and overflows

### ISSUE THREAD

**Issue by mikerockett** [ryancramerdesign/AdminThemeUikit#45]
Something that's bugged me from the default theme since the beginning is the drops downs and how they require one to scroll the page to access more items. I'm sure this has been mentioned before, somewhere, but I think it's quite important that the methodology changes in this admin theme before it reaches feature parity, ready for core-inclusion.

My suggestions are:

1. Prevent drop down heights from exceeding the viewport height. A scroll bar should be used, as opposed to scrolling the entire view to access more of the drop down.
2. Increasing the sub-menu padding for consistency -- all drop down items should have the same padding. I think I might know why it's done the way it is now (menus vs lists), but the inconsistency doesn't feel right, and it surely doesn't match the larger padding scheme used throughout the theme.
3. One of the very few things things I like about Bootstrap is that menus are click-to-drop. I think menus should behave like they do on a desktop. Hover-to-drop feels somewhat old-school. Click for the first drop, and then sub-menus can appear on hover (delay or no delay, it doesn't matter). From a UX view-point, this *could* mean using carets to indicate menus, but it isn't a requirement...

Thanks for your excellent work on this Ryan - PW is starting to show its 'new colors'.

**Comment by ryancramerdesign** [comment]
> Prevent drop down heights from exceeding the viewport height. A scroll bar should be used, as opposed to scrolling the entire view to access more of the drop down.

Hmm, I don't agree, I would expect dropdown to work the same as everything else on the page with regard to scrolling. It sounds like you think it should behave like an iframe with it's own scrollbar in the dropdown? It sounds unconventional and interesting, but that could get pretty ugly, especially on the platforms that show visible scrollbars, and there's definitely not room for scrollbars in the dropdowns. 

> Increasing the sub-menu padding for consistency -- all drop down items should have the same padding. I think I might know why it's done the way it is now (menus vs lists), but the inconsistency doesn't feel right, and it surely doesn't match the larger padding scheme used throughout the theme.

Not positive I know exactly what you are talking about without a screenshot. But if you are referring to the navigation items like Setup > Templates, or Setup > Fields, relative to their items (list of templates or fields) then yes, we do use a very different line height for these. They are a different animal, can potentially have hundreds of items, so the treatment is intentionally different by design. I think this needs to be the case, but maybe there's room for improvement in the styling? 

> One of the very few things things I like about Bootstrap is that menus are click-to-drop. I think menus should behave like they do on a desktop. Hover-to-drop feels somewhat old-school. 

I feel the opposite with regard to click-to-drop vs hover. In a browser, when you click something, there is an expectation that navigation will/could occur (as in change of URL). There's no such expectation connected with hover. But I also recognize it's subjective, and open to making it a configurable option with the admin theme, assuming jQuery UI supports the option (I think it does).

**Comment by ryancramerdesign** [comment]
Looking into click-to-drop option, we'd have to double-up all of the navigation items having children. One to actually click the navigate to the location, and another to reveal its children/subnav. We do that in our mobile sidebar nav, but it's navigationally more cumbersome—more items to look at, and more steps to get to the same place. Of course, it's fine for mobile/touch nav since there is no such thing as a hover there. But enabling for topnav doesn't look like it's as simple as a configurable toggle, because the nav would have to be much more loaded up with stuff. You mentioned bootstrap uses this click-to-show subnav. How do they handle the situation where you want to click to navigate vs click to reveal subnav on the same item?

**Comment by mikerockett** [comment]
> Hmm, I don't agree, I would expect dropdown to work the same as everything else on the page with regard to scrolling. It sounds like you think it should behave like an iframe with it's own scrollbar in the dropdown? It sounds unconventional and interesting, but that could get pretty ugly, especially on the platforms that show visible scrollbars, and there's definitely not room for scrollbars in the dropdowns.

My main issue with the hover route is that if the drop-list is long and I accidentally move my mouse away after having scrolled down to the item I want, the menu disappears and I need to go back up to re-open it. So yes, it would need to behave like an iframe. Perhaps a JS-based scrollbar would help for the purposes of persistency? It could be light (transparent) and, say, 4px thick so that it doesn't scream at you, but is still easily seen.

> They are a different animal, can potentially have hundreds of items, so the treatment is intentionally different by design.

I thought they may be the case. It's not a big issue, especially if it's by design. I think the inconsistency bugged me somewhat, and that a self-contained scrolling menu (as above) would help iron things out in this regard as well. That said, itf its by design, then it's no biggie.

> In a browser, when you click something, there is an expectation that navigation will/could occur (as in change of URL)

With SPAs popping up all over the show, the web is starting to become a more app-like environment, where a click could well mean a menu or modal will pop up, so I do think the flexibility should be there. I'm very used to clicking for initial menus, and so this is just something that's been an annoyance for me.

> Looking into click-to-drop option, we'd have to double-up all of the navigation items having children. One to actually click the navigate to the location, and another to reveal its children/subnav. 

I think that a sub-menu hover is fine — that's how it behaves in Windows and other OSes anyway. So, for me, it's as I'd expect it be. It does, however, retain the issue in terms of scrolling a long sub-menu drop and accidentally loosing it due to mouse movement. I think there are hover-intent plugins that solve the issue, where the menu will only disappear if the user 'intends' to keep the mouse away, say after one or two seconds.

> You mentioned bootstrap uses this click-to-show subnav. How do they handle the situation where you want to click to navigate vs click to reveal subnav on the same item?

Generally, a click-to-drop menu will not have both behaviours. As such, `href` is simply a the pound sign or it's default click event is prevented (though, that's just bad practise). In our case, that would mean a link to the Setup Page, for example, would no longer exist. However, I've never used it, and I can't imagine many folks do, as everything that's available in Setup is also available in the drop.
